### ISSUE TITLE
logic level converter

### ISSUE THREAD

**Issue by zoldaten** [ibrahimqazi/TFmini-Plus-LiDAR-interfacing-with-Raspberr-Pi#2]
hi!
thanks for the code. works like a charm.
but i think we need logic level converter to safe raspberry pi pins as it operates 3v level.
something like this:
![logic level converter](https://user-images.githubusercontent.com/29411817/229712295-3bcd2317-ae14-470f-a1c3-1c265ae36c95.png)
so, as we have two pins RX and TX, they go to logic level converter.

i tested, it works.
but i also  have to change uart line like this:
`ser = serial.Serial("/dev/ttyS0", 115200)`

one more question:
1. what does it mean 'strength' in output?
2. why temperature is wrong ? i see 43 but i really have 25.

**Comment by ibrahimqazi** [comment]
Hello,
Don't need for logic level converter, if you look at the datasheet of sensor, its written that logic level is 3.3V not 5V.
![image](https://user-images.githubusercontent.com/8738199/229746887-2e763727-bd7a-464b-b1c6-d2d97954a77d.png)

`ser = serial.Serial("/dev/ttyS0", 115200)` > This varies from system to system so everyone needs to adjust it according to their port number.

Strength is signal strength.

why temperature is wrong ? i see 43 but i really have 25. > its not environment temperature but chip internal temperature.

I would suggest you to go through manual and datasheet to have basic understanding of sensor.

**Comment by zoldaten** [comment]
got it. thanks.
